[package]
name = "fsevents_parser_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
regex = "1.6.0"
flate2 = "1.0.24"
bitflags = "1.3.2"